### ISSUE TITLE
BetterJoyForCemu broken with the new Windows build 1903?

### ISSUE THREAD

**Issue by Cottontails** [Davidobot/BetterJoyForCemu#173]
After updating to the latest version of Windows 10 (the 1903 update), BetterJoyForCemu appears to no longer work, when i launch a game there is no functionality, not even in Cemu. Upon connecting the Pro controller the dots lag continuously but it appeared to connect anyways, it also failed to vibrate when clicking the locate button. So i tried uninstalling the driver and updated to the latest version of the program and reinstalled the driver to no avail. Is anyone else having problems with the new update?

**Comment by v5tge** [comment]
Same here. It looks like the virtual xbox controller is not appearing, so this app is no longer working in this version, at least in my case. I'm uninstalling the drivers for now and let's see if there is an easy solution for this.

**Comment by Cottontails** [comment]
If you find out anything, please let me know.

**Comment by v5tge** [comment]
ok, I'm not 100% sure about what i did, but I closed the app, removed all devices from hidguardian configuration (following the first thing that appears in the problems section) and uninstalled the drivers.
Then I reinstalled them and launched the program again with the controller off, and when I connected it a notification showed up saying that a new xbox controller was being configured. In game devices (you can search "controller" and it should appears) click properties and there you can check if the controller is working, and how many controllers there are. the only one that should work is the xbox 360 controller. If the switch pro controller is on the list it shouldn't receive any input.
I don't know why but everything seems to be working properly now for me.

**Comment by v5tge** [comment]
if the device don't shows up in hidguardian list try opening betterjoy for cemu again

**Comment by Cottontails** [comment]
That fixed it thanks very much :D

**Comment by Owlious** [comment]
same problem here.My windows version is also 1903.pro controller only works well the first time it connect with Bluetooth, when I disconnect the controller and try to reconnect, windows seems to be unable to recognize the controller as an virtual Xbox controller or Pro controller.So the only way to make it work well is to remove the device from windows and connect to system initially like it has not connect before.
I think it must be something wrong with the 1903 version, and the solution above doesn`t work.I reinstall all the device drivers and programs again,but the problem is still there.Is there anyone ever meet the same problem?
